[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GBIF2 = "dedd4f52-e074-43bf-924d-d6bce14ad628"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartoNotebookRunner = "4c0109c6-14e9-4c88-93f0-2b974d3468f4"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
